apiVersion: batch/v1
kind: Job
metadata:
  name: llm-training-job
spec:
  completions: 4       # total pods to complete
  parallelism: 2       # max pods running at the same time
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchLabels:
                    app: llm-training
      containers:
      - name: llm-training
        image: kshitijhatwar/llm-train:latest
        resources:
          requests:
            memory: "4Gi"
            cpu: "4"
          limits:
            memory: "9Gi"
            cpu: "9"
        volumeMounts:
        - name: llm-data
          mountPath: /app/data
      volumes:
      - name: llm-data
        persistentVolumeClaim:
          claimName: llm-data-pvc
