apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-data-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
